name: Check Version
on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:
jobs:
  check_version:
    runs-on: ubuntu-latest
    steps:
    - name: Check version
      run: |
        # Get version from QEMU
        QEMU_V=$(wget -qO- https://gitlab.com/api/v4/projects/11167699/repository/tags | jq -r '[.[] | select(.name | test("-(rc|beta|alpha)"; "i") | not)] | .[].name' | sort -V | tail -1)
        
        # Get version from this repo
        AVAILABLE_V=$(curl -s \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${{ github.repository }}/releases/latest" | jq -r '.tag_name')
        
        # Check if versions are empty or null
        if [ -z "$QEMU_V" ] || [ "$QEMU_V" = "null" ] || [ -z "$AVAILABLE_V" ] || [ "$AVAILABLE_V" = "null" ]; then
          echo "Couldn't get Version numbers"
          exit 1
        fi
        
        if [ "${QEMU_V#v}" != "${AVAILABLE_V#v}" ]; then
          echo "Newer version found: v${QEMU_V#v}"
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/actions/workflows/qemu.yml/dispatches" \
            -d "{\"ref\":\"master\"}"
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/actions/workflows/qemu_arm.yml/dispatches" \
            -d "{\"ref\":\"master\"}"
        else
          echo "Nothing to do"
        fi
